### ISSUE TITLE
Developed base IaC modules in terraform

### ISSUE THREAD

**Issue by FridayPush** [FridayPush/chess-platform#3]
To ensure that we have the same infrastructure in testing as in prod we'll create a series of terraform modules to ensure that the resources are managed identically. Additionally this will allow our CI/CD platform to deploy environments for integration tests. 

### Assumptions
- Only serving USA based users
- All modules must have tests and examples
- Only targeting GCP, vendor lock-in is ok
- Modules revisions are not expected to be backward compatible

### Tasks
- [ ] VPC / Subnet configuration
- [ ] Primary service account creations
- [ ] Configuration of EndPoint service
- [ ] GCE single instance module
- [ ] GKE module
